/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRelatoriosRouteImport } from './routes/_app/relatorios'
import { Route as AppProdutosRouteImport } from './routes/_app/produtos'
import { Route as AppPdvRouteImport } from './routes/_app/pdv'
import { Route as AppOrcamentosRouteImport } from './routes/_app/orcamentos'
import { Route as AppInadimplenciaRouteImport } from './routes/_app/inadimplencia'
import { Route as AppGarrafasRouteImport } from './routes/_app/garrafas'
import { Route as AppFluxoCaixaRouteImport } from './routes/_app/fluxo-caixa'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppContasPagarRouteImport } from './routes/_app/contas-pagar'
import { Route as AppClientesRouteImport } from './routes/_app/clientes'
import { Route as AppCategoriasRouteImport } from './routes/_app/categorias'
import { Route as AppCaixaRouteImport } from './routes/_app/caixa'
import { Route as AppCadernetaRouteImport } from './routes/_app/caderneta'
import { Route as AppVendasHistoricoRouteImport } from './routes/_app/vendas.historico'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRelatoriosRoute = AppRelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => AppRoute,
} as any)
const AppProdutosRoute = AppProdutosRouteImport.update({
  id: '/produtos',
  path: '/produtos',
  getParentRoute: () => AppRoute,
} as any)
const AppPdvRoute = AppPdvRouteImport.update({
  id: '/pdv',
  path: '/pdv',
  getParentRoute: () => AppRoute,
} as any)
const AppOrcamentosRoute = AppOrcamentosRouteImport.update({
  id: '/orcamentos',
  path: '/orcamentos',
  getParentRoute: () => AppRoute,
} as any)
const AppInadimplenciaRoute = AppInadimplenciaRouteImport.update({
  id: '/inadimplencia',
  path: '/inadimplencia',
  getParentRoute: () => AppRoute,
} as any)
const AppGarrafasRoute = AppGarrafasRouteImport.update({
  id: '/garrafas',
  path: '/garrafas',
  getParentRoute: () => AppRoute,
} as any)
const AppFluxoCaixaRoute = AppFluxoCaixaRouteImport.update({
  id: '/fluxo-caixa',
  path: '/fluxo-caixa',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppContasPagarRoute = AppContasPagarRouteImport.update({
  id: '/contas-pagar',
  path: '/contas-pagar',
  getParentRoute: () => AppRoute,
} as any)
const AppClientesRoute = AppClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => AppRoute,
} as any)
const AppCategoriasRoute = AppCategoriasRouteImport.update({
  id: '/categorias',
  path: '/categorias',
  getParentRoute: () => AppRoute,
} as any)
const AppCaixaRoute = AppCaixaRouteImport.update({
  id: '/caixa',
  path: '/caixa',
  getParentRoute: () => AppRoute,
} as any)
const AppCadernetaRoute = AppCadernetaRouteImport.update({
  id: '/caderneta',
  path: '/caderneta',
  getParentRoute: () => AppRoute,
} as any)
const AppVendasHistoricoRoute = AppVendasHistoricoRouteImport.update({
  id: '/vendas/historico',
  path: '/vendas/historico',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/caderneta': typeof AppCadernetaRoute
  '/caixa': typeof AppCaixaRoute
  '/categorias': typeof AppCategoriasRoute
  '/clientes': typeof AppClientesRoute
  '/contas-pagar': typeof AppContasPagarRoute
  '/dashboard': typeof AppDashboardRoute
  '/fluxo-caixa': typeof AppFluxoCaixaRoute
  '/garrafas': typeof AppGarrafasRoute
  '/inadimplencia': typeof AppInadimplenciaRoute
  '/orcamentos': typeof AppOrcamentosRoute
  '/pdv': typeof AppPdvRoute
  '/produtos': typeof AppProdutosRoute
  '/relatorios': typeof AppRelatoriosRoute
  '/vendas/historico': typeof AppVendasHistoricoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/caderneta': typeof AppCadernetaRoute
  '/caixa': typeof AppCaixaRoute
  '/categorias': typeof AppCategoriasRoute
  '/clientes': typeof AppClientesRoute
  '/contas-pagar': typeof AppContasPagarRoute
  '/dashboard': typeof AppDashboardRoute
  '/fluxo-caixa': typeof AppFluxoCaixaRoute
  '/garrafas': typeof AppGarrafasRoute
  '/inadimplencia': typeof AppInadimplenciaRoute
  '/orcamentos': typeof AppOrcamentosRoute
  '/pdv': typeof AppPdvRoute
  '/produtos': typeof AppProdutosRoute
  '/relatorios': typeof AppRelatoriosRoute
  '/vendas/historico': typeof AppVendasHistoricoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/caderneta': typeof AppCadernetaRoute
  '/_app/caixa': typeof AppCaixaRoute
  '/_app/categorias': typeof AppCategoriasRoute
  '/_app/clientes': typeof AppClientesRoute
  '/_app/contas-pagar': typeof AppContasPagarRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/fluxo-caixa': typeof AppFluxoCaixaRoute
  '/_app/garrafas': typeof AppGarrafasRoute
  '/_app/inadimplencia': typeof AppInadimplenciaRoute
  '/_app/orcamentos': typeof AppOrcamentosRoute
  '/_app/pdv': typeof AppPdvRoute
  '/_app/produtos': typeof AppProdutosRoute
  '/_app/relatorios': typeof AppRelatoriosRoute
  '/_app/vendas/historico': typeof AppVendasHistoricoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/caderneta'
    | '/caixa'
    | '/categorias'
    | '/clientes'
    | '/contas-pagar'
    | '/dashboard'
    | '/fluxo-caixa'
    | '/garrafas'
    | '/inadimplencia'
    | '/orcamentos'
    | '/pdv'
    | '/produtos'
    | '/relatorios'
    | '/vendas/historico'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/caderneta'
    | '/caixa'
    | '/categorias'
    | '/clientes'
    | '/contas-pagar'
    | '/dashboard'
    | '/fluxo-caixa'
    | '/garrafas'
    | '/inadimplencia'
    | '/orcamentos'
    | '/pdv'
    | '/produtos'
    | '/relatorios'
    | '/vendas/historico'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/_app/caderneta'
    | '/_app/caixa'
    | '/_app/categorias'
    | '/_app/clientes'
    | '/_app/contas-pagar'
    | '/_app/dashboard'
    | '/_app/fluxo-caixa'
    | '/_app/garrafas'
    | '/_app/inadimplencia'
    | '/_app/orcamentos'
    | '/_app/pdv'
    | '/_app/produtos'
    | '/_app/relatorios'
    | '/_app/vendas/historico'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/relatorios': {
      id: '/_app/relatorios'
      path: '/relatorios'
      fullPath: '/relatorios'
      preLoaderRoute: typeof AppRelatoriosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/produtos': {
      id: '/_app/produtos'
      path: '/produtos'
      fullPath: '/produtos'
      preLoaderRoute: typeof AppProdutosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/pdv': {
      id: '/_app/pdv'
      path: '/pdv'
      fullPath: '/pdv'
      preLoaderRoute: typeof AppPdvRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/orcamentos': {
      id: '/_app/orcamentos'
      path: '/orcamentos'
      fullPath: '/orcamentos'
      preLoaderRoute: typeof AppOrcamentosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/inadimplencia': {
      id: '/_app/inadimplencia'
      path: '/inadimplencia'
      fullPath: '/inadimplencia'
      preLoaderRoute: typeof AppInadimplenciaRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/garrafas': {
      id: '/_app/garrafas'
      path: '/garrafas'
      fullPath: '/garrafas'
      preLoaderRoute: typeof AppGarrafasRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/fluxo-caixa': {
      id: '/_app/fluxo-caixa'
      path: '/fluxo-caixa'
      fullPath: '/fluxo-caixa'
      preLoaderRoute: typeof AppFluxoCaixaRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/contas-pagar': {
      id: '/_app/contas-pagar'
      path: '/contas-pagar'
      fullPath: '/contas-pagar'
      preLoaderRoute: typeof AppContasPagarRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/clientes': {
      id: '/_app/clientes'
      path: '/clientes'
      fullPath: '/clientes'
      preLoaderRoute: typeof AppClientesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/categorias': {
      id: '/_app/categorias'
      path: '/categorias'
      fullPath: '/categorias'
      preLoaderRoute: typeof AppCategoriasRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/caixa': {
      id: '/_app/caixa'
      path: '/caixa'
      fullPath: '/caixa'
      preLoaderRoute: typeof AppCaixaRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/caderneta': {
      id: '/_app/caderneta'
      path: '/caderneta'
      fullPath: '/caderneta'
      preLoaderRoute: typeof AppCadernetaRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/vendas/historico': {
      id: '/_app/vendas/historico'
      path: '/vendas/historico'
      fullPath: '/vendas/historico'
      preLoaderRoute: typeof AppVendasHistoricoRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppCadernetaRoute: typeof AppCadernetaRoute
  AppCaixaRoute: typeof AppCaixaRoute
  AppCategoriasRoute: typeof AppCategoriasRoute
  AppClientesRoute: typeof AppClientesRoute
  AppContasPagarRoute: typeof AppContasPagarRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppFluxoCaixaRoute: typeof AppFluxoCaixaRoute
  AppGarrafasRoute: typeof AppGarrafasRoute
  AppInadimplenciaRoute: typeof AppInadimplenciaRoute
  AppOrcamentosRoute: typeof AppOrcamentosRoute
  AppPdvRoute: typeof AppPdvRoute
  AppProdutosRoute: typeof AppProdutosRoute
  AppRelatoriosRoute: typeof AppRelatoriosRoute
  AppVendasHistoricoRoute: typeof AppVendasHistoricoRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppCadernetaRoute: AppCadernetaRoute,
  AppCaixaRoute: AppCaixaRoute,
  AppCategoriasRoute: AppCategoriasRoute,
  AppClientesRoute: AppClientesRoute,
  AppContasPagarRoute: AppContasPagarRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppFluxoCaixaRoute: AppFluxoCaixaRoute,
  AppGarrafasRoute: AppGarrafasRoute,
  AppInadimplenciaRoute: AppInadimplenciaRoute,
  AppOrcamentosRoute: AppOrcamentosRoute,
  AppPdvRoute: AppPdvRoute,
  AppProdutosRoute: AppProdutosRoute,
  AppRelatoriosRoute: AppRelatoriosRoute,
  AppVendasHistoricoRoute: AppVendasHistoricoRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
