/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRelatoriosRouteImport } from './routes/_app/relatorios'
import { Route as AppProdutosRouteImport } from './routes/_app/produtos'
import { Route as AppPdvRouteImport } from './routes/_app/pdv'
import { Route as AppFluxoCaixaRouteImport } from './routes/_app/fluxo-caixa'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppClientesRouteImport } from './routes/_app/clientes'
import { Route as AppCategoriasRouteImport } from './routes/_app/categorias'
import { Route as AppCadernetaRouteImport } from './routes/_app/caderneta'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRelatoriosRoute = AppRelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => AppRoute,
} as any)
const AppProdutosRoute = AppProdutosRouteImport.update({
  id: '/produtos',
  path: '/produtos',
  getParentRoute: () => AppRoute,
} as any)
const AppPdvRoute = AppPdvRouteImport.update({
  id: '/pdv',
  path: '/pdv',
  getParentRoute: () => AppRoute,
} as any)
const AppFluxoCaixaRoute = AppFluxoCaixaRouteImport.update({
  id: '/fluxo-caixa',
  path: '/fluxo-caixa',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppClientesRoute = AppClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => AppRoute,
} as any)
const AppCategoriasRoute = AppCategoriasRouteImport.update({
  id: '/categorias',
  path: '/categorias',
  getParentRoute: () => AppRoute,
} as any)
const AppCadernetaRoute = AppCadernetaRouteImport.update({
  id: '/caderneta',
  path: '/caderneta',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/caderneta': typeof AppCadernetaRoute
  '/categorias': typeof AppCategoriasRoute
  '/clientes': typeof AppClientesRoute
  '/dashboard': typeof AppDashboardRoute
  '/fluxo-caixa': typeof AppFluxoCaixaRoute
  '/pdv': typeof AppPdvRoute
  '/produtos': typeof AppProdutosRoute
  '/relatorios': typeof AppRelatoriosRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/caderneta': typeof AppCadernetaRoute
  '/categorias': typeof AppCategoriasRoute
  '/clientes': typeof AppClientesRoute
  '/dashboard': typeof AppDashboardRoute
  '/fluxo-caixa': typeof AppFluxoCaixaRoute
  '/pdv': typeof AppPdvRoute
  '/produtos': typeof AppProdutosRoute
  '/relatorios': typeof AppRelatoriosRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/caderneta': typeof AppCadernetaRoute
  '/_app/categorias': typeof AppCategoriasRoute
  '/_app/clientes': typeof AppClientesRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/fluxo-caixa': typeof AppFluxoCaixaRoute
  '/_app/pdv': typeof AppPdvRoute
  '/_app/produtos': typeof AppProdutosRoute
  '/_app/relatorios': typeof AppRelatoriosRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/caderneta'
    | '/categorias'
    | '/clientes'
    | '/dashboard'
    | '/fluxo-caixa'
    | '/pdv'
    | '/produtos'
    | '/relatorios'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/caderneta'
    | '/categorias'
    | '/clientes'
    | '/dashboard'
    | '/fluxo-caixa'
    | '/pdv'
    | '/produtos'
    | '/relatorios'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/_app/caderneta'
    | '/_app/categorias'
    | '/_app/clientes'
    | '/_app/dashboard'
    | '/_app/fluxo-caixa'
    | '/_app/pdv'
    | '/_app/produtos'
    | '/_app/relatorios'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/relatorios': {
      id: '/_app/relatorios'
      path: '/relatorios'
      fullPath: '/relatorios'
      preLoaderRoute: typeof AppRelatoriosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/produtos': {
      id: '/_app/produtos'
      path: '/produtos'
      fullPath: '/produtos'
      preLoaderRoute: typeof AppProdutosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/pdv': {
      id: '/_app/pdv'
      path: '/pdv'
      fullPath: '/pdv'
      preLoaderRoute: typeof AppPdvRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/fluxo-caixa': {
      id: '/_app/fluxo-caixa'
      path: '/fluxo-caixa'
      fullPath: '/fluxo-caixa'
      preLoaderRoute: typeof AppFluxoCaixaRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/clientes': {
      id: '/_app/clientes'
      path: '/clientes'
      fullPath: '/clientes'
      preLoaderRoute: typeof AppClientesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/categorias': {
      id: '/_app/categorias'
      path: '/categorias'
      fullPath: '/categorias'
      preLoaderRoute: typeof AppCategoriasRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/caderneta': {
      id: '/_app/caderneta'
      path: '/caderneta'
      fullPath: '/caderneta'
      preLoaderRoute: typeof AppCadernetaRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppCadernetaRoute: typeof AppCadernetaRoute
  AppCategoriasRoute: typeof AppCategoriasRoute
  AppClientesRoute: typeof AppClientesRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppFluxoCaixaRoute: typeof AppFluxoCaixaRoute
  AppPdvRoute: typeof AppPdvRoute
  AppProdutosRoute: typeof AppProdutosRoute
  AppRelatoriosRoute: typeof AppRelatoriosRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppCadernetaRoute: AppCadernetaRoute,
  AppCategoriasRoute: AppCategoriasRoute,
  AppClientesRoute: AppClientesRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppFluxoCaixaRoute: AppFluxoCaixaRoute,
  AppPdvRoute: AppPdvRoute,
  AppProdutosRoute: AppProdutosRoute,
  AppRelatoriosRoute: AppRelatoriosRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
